INSERT INTO [dbo].[Time_Registration] ([id_user], [id_project], [hours], [user_notes], [date], [work_category]) VALUES (1, 1, 2, N'ijqwduihqwed wec', N'2015-04-12 14:39:55', N'Bug Fix')
INSERT INTO [dbo].[Time_Registration] ([id_user], [id_project], [hours], [user_notes], [date], [work_category]) VALUES (14, 5, 15, N'dqwdqwdfwe23', N'2015-04-12 17:04:32', N'New Feature')
INSERT INTO [dbo].[Time_Registration] ([id_user], [id_project], [hours], [user_notes], [date], [work_category]) VALUES (14, 1, 3, N'asdqwfgq', N'2015-04-12 21:43:50', N'New Feature')
INSERT INTO [dbo].[Time_Registration] ([id_user], [id_project], [hours], [user_notes], [date], [work_category]) VALUES (14, 5, 2, N'12eqwdqwf', N'2015-04-12 21:47:39', N'New Feature')
INSERT INTO [dbo].[Time_Registration] ([id_user], [id_project], [hours], [user_notes], [date], [work_category]) VALUES (14, 1, 3, N'qwd12ed', N'2015-04-12 21:52:44', N'Bug Fix')
INSERT INTO [dbo].[Time_Registration] ([id_user], [id_project], [hours], [user_notes], [date], [work_category]) VALUES (14, 5, 1, N'qwed', N'2015-04-12 21:52:58', N'New Feature')
INSERT INTO [dbo].[Time_Registration] ([id_user], [id_project], [hours], [user_notes], [date], [work_category]) VALUES (14, 1, 3, N'qwdqwf', N'2015-04-12 21:53:05', N'New Feature')
INSERT INTO [dbo].[Time_Registration] ([id_user], [id_project], [hours], [user_notes], [date], [work_category]) VALUES (14, 1, 3, N'qdwcdasfwsdf', N'2015-04-12 21:55:53', N'New Feature')
INSERT INTO [dbo].[Time_Registration] ([id_user], [id_project], [hours], [user_notes], [date], [work_category]) VALUES (14, 1, 3, N'qwdqwfqwf', N'2015-04-12 21:58:19', N'New Feature')
INSERT INTO [dbo].[Time_Registration] ([id_user], [id_project], [hours], [user_notes], [date], [work_category]) VALUES (14, 1, 2, N'qwdqwd', N'2015-04-12 22:01:07', N'Extra Hours')
INSERT INTO [dbo].[Time_Registration] ([id_user], [id_project], [hours], [user_notes], [date], [work_category]) VALUES (14, 1, 1, N'dqwdqwf', N'2015-04-12 22:01:18', N'New Feature')
INSERT INTO [dbo].[Time_Registration] ([id_user], [id_project], [hours], [user_notes], [date], [work_category]) VALUES (14, 5, 1, N'qwefdasfsdf', N'2015-04-12 22:01:26', N'Extra Hours')
INSERT INTO [dbo].[Time_Registration] ([id_user], [id_project], [hours], [user_notes], [date], [work_category]) VALUES (14, 5, 1, N'qwd', N'2015-04-12 22:03:39', N'New Feature')
INSERT INTO [dbo].[Time_Registration] ([id_user], [id_project], [hours], [user_notes], [date], [work_category]) VALUES (1, 1, 3, N'added feature ', N'2015-04-12 22:06:41', N'New Feature')
INSERT INTO [dbo].[Time_Registration] ([id_user], [id_project], [hours], [user_notes], [date], [work_category]) VALUES (1, 5, 10, N'Added new release feqature button', N'2015-04-12 22:09:33', N'New Feature')
INSERT INTO [dbo].[Time_Registration] ([id_user], [id_project], [hours], [user_notes], [date], [work_category]) VALUES (14, 1, 0, N'qwdqwd', N'2015-04-13 01:13:12', N'New Feature')
INSERT INTO [dbo].[Time_Registration] ([id_user], [id_project], [hours], [user_notes], [date], [work_category]) VALUES (14, 1, 0, N'testest', N'2015-04-13 01:20:20', N'New Feature')
INSERT INTO [dbo].[Time_Registration] ([id_user], [id_project], [hours], [user_notes], [date], [work_category]) VALUES (1, 1, 0, N'wdqwdqwdqwd', N'2015-04-13 01:22:57', N'New Feature')
INSERT INTO [dbo].[Time_Registration] ([id_user], [id_project], [hours], [user_notes], [date], [work_category]) VALUES (1, 1, 0, N'testestes', N'2015-04-13 01:23:51', N'New Feature')
INSERT INTO [dbo].[Time_Registration] ([id_user], [id_project], [hours], [user_notes], [date], [work_category]) VALUES (14, 10, 0, N'qwdqwfqwf', N'2015-04-14 13:04:17', N'Bug Fix')
